name: 🐞 Bug Report
description: Report a Bug for a deployed ESPD service
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: what-happened
    attributes:
      label: Details of the observed situation
      description: Full description of the observed behaviour vs. the expected behaviour
      placeholder: "Please provide the following information: the link of the ESDP service, the expected behaiour, the observed behaviour, the reference to the ANNEX 2 of Regulation (EU) 2016/7"  
      value: |
        Please provide the following information: 
         - the link of the ESDP service, 
         - the expected behaiour, 
         - the observed behaviour, 
         - the reference to the ANNEX 2 of Regulation (EU) 2016/7
         - you may add print screens in the comments after creating the BUG issue
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ESPD Version
      description: Which version of ESPD EDM are you running?
      options:
        - 1.0.1
        - 1.0.2 (Default)
        - 2.0.0
        - 2.0.1
        - 2.0.2
        - 2.1.0
        - 2.1.1
        - 3.0.0
        - 3.0.1
        - 3.1.0
        - 3.2.0
        - 3.3.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

