name: ✨ New Feature Request
description: Reqeust a new feature for ESPD EDM
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature request! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: user-requirements
    attributes:
      label: Full details of the new feature
      description: Full description of the new feature and the desired behaviour
      placeholder: "Please provide the following information: full description of new requirement, the expected behaiour, the reference to the ANNEX 2 of Regulation (EU) 2016/7"  
      value: |
        Please provide the following information: 
         - full description of new requirement, 
         - the expected behaiour,  
         - the reference to the ANNEX 2 of Regulation (EU) 2016/7
         - you may add print screens in the comments after creating the FEATURE request
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ESPD Version
      description: Which version of ESPD EDM is this feature to be implemented?
      options:
        - 3.0.0
        - 3.0.1
        - 3.1.0
        - 3.2.0
        - 3.3.0 (Default)
        - next
        - future
      default: 0
    validations:
      required: true