name: 🔧 Implementation Information Request
description: Implementation information request about ESPD EDM
title: "[Implementation]: "
labels: ["help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this implementation information request! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: user-question
    attributes:
      label: Full details of the implementation information request
      description: Full description of the implementation information request
      placeholder: "Please provide the following information: full description of the implementation information request"  
      value: |
        Please provide the following information: 
         - full description of the implementation information request, 
         - the reference to the ANNEX 2 of Regulation (EU) 2016/7, if applicable
         - you may add print screens in the comments after creating the IMPLEMENTATION information request
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ESPD Version
      description: Which version of ESPD EDM is this IMPLEMENTATION refering to?
      options:
        - 1.0.1
        - 1.0.2
        - 2.0.0
        - 2.0.1
        - 2.0.2
        - 2.1.0
        - 2.1.1
        - 3.0.0
        - 3.0.1
        - 3.1.0
        - 3.2.0
        - 3.3.0 (Default)
        - next
        - future
      default: 0
    validations:
      required: true